FROM envoyproxy/envoy-dev:latest

COPY ./jwks.json /etc/envoy/jwks.json

RUN apt-get update && apt-get -q install -y \
    curl
CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
